# Generated by Django 4.1.7 on 2023-03-25 18:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='covers/')),
            ],
        ),
        migrations.CreateModel(
            name='TattooArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('via', models.CharField(max_length=60)),
                ('citta', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=60)),
                ('cap', models.CharField(max_length=10)),
                ('descrizione', models.TextField(blank=True, max_length=256)),
                ('email', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TattooStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stile', models.CharField(max_length=30)),
                ('tattoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stiliTatuatori', to='api.tattoo')),
            ],
        ),
        migrations.CreateModel(
            name='TattooArtistStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stile', models.CharField(max_length=30)),
                ('tattooArtist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stiliTatuatori', to='api.tattooartist')),
            ],
        ),
        migrations.CreateModel(
            name='TattooArtistPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfondo', models.ImageField(upload_to='covers/')),
                ('tattooArtist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sfondiTatuatore', to='api.tattooartist')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(blank=True, max_length=256)),
                ('voto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tattooArtist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tattooartist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tattooArtist')},
                'index_together': {('user', 'tattooArtist')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('TattooArtist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tattooartist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'TattooArtist')},
                'index_together': {('user', 'TattooArtist')},
            },
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tattoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tattooFav', to='api.tattoo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utenteFav', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tattoo')},
                'index_together': {('user', 'tattoo')},
            },
        ),
    ]
