# Generated by Django 4.1.7 on 2023-04-08 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoo',
            name='tattooArtist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.tattooartist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favourites',
            name='tattoo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tattoo'),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tattooartistphoto',
            name='tattooArtist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tattooartist'),
        ),
        migrations.AlterField(
            model_name='tattooartiststyle',
            name='tattooArtist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tattooartist'),
        ),
        migrations.AlterField(
            model_name='tattoostyle',
            name='tattoo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tattoo'),
        ),
    ]
