# Generated by Django 4.1.7 on 2023-04-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_tattooartist_rating_tattooartist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
